<?php
class phperror_class {
    var $version;
    var $error_reporting;
    var $error_decode;
    var $log_errors;
    var $error_log;
    var $decode=array();
    var $code=array();
    function __construct($decode=0) {
        $this->version=phpversion();
        $this->error_reporting=error_reporting();
        $this->error_log=ini_get('log_errors');
        $this->error_log=ini_get('error_log');
		if (E_ERROR) $this->code[E_ERROR]=new phperror_code_class('E_ERROR',"Fatal run-time errors. These indicate errors that can not be recovered from, such as a memory allocation problem. Execution of the script is halted.");
        if (E_WARNING) $this->code[E_WARNING]=new phperror_code_class('E_WARNING',"Run-time warnings (non-fatal errors). Execution of the script is not halted.");
        if (E_PARSE) $this->code[E_PARSE]=new phperror_code_class('E_PARSE',"Compile-time parse errors. Parse errors should only be generated by the parser.");
        if (E_NOTICE) $this->code[E_NOTICE]=new phperror_code_class('E_NOTICE',"Run-time notices. Indicate that the script encountered something that could indicate an error, but could also happen in the normal course of running a script.");
        if (E_CORE_ERROR) $this->code[E_CORE_ERROR]=new phperror_code_class('E_CORE_ERROR',"Fatal errors that occur during PHP's initial startup. This is like an E_ERROR, except it is generated by the core of PHP.  Since PHP 4");
        if (E_CORE_WARNING) $this->code[E_CORE_WARNING]=new phperror_code_class('E_CORE_WARNING',"Warnings (non-fatal errors) that occur during PHP's initial startup. This is like an E_WARNING, except it is generated by the core of PHP.  Since PHP 4");
        if (E_COMPILE_ERROR) $this->code[E_COMPILE_ERROR]=new phperror_code_class('E_COMPILE_ERROR',"Fatal compile-time errors. This is like an E_ERROR, except it is generated by the Zend Scripting Engine.  Since PHP 4");
        if (E_COMPILE_WARNING) $this->code[E_COMPILE_WARNING]=new phperror_code_class('E_COMPILE_WARNING',"Compile-time warnings (non-fatal errors). This is like an E_WARNING, except it is generated by the Zend Scripting Engine.  Since PHP 4");
        if (E_USER_ERROR) $this->code[E_USER_ERROR]=new phperror_code_class('E_USER_ERROR',"User-generated error message. This is like an E_ERROR, except it is generated in PHP code by using the PHP function trigger_error().  Since PHP 4");
        if (E_USER_WARNING) $this->code[E_USER_WARNING]=new phperror_code_class('E_USER_WARNING',"User-generated warning message. This is like an E_WARNING, except it is generated in PHP code by using the PHP function trigger_error().  Since PHP 4");
        if (E_USER_NOTICE) $this->code[E_USER_NOTICE]=new phperror_code_class('E_USER_NOTICE',"User-generated notice message. This is like an E_NOTICE, except it is generated in PHP code by using the PHP function trigger_error().  Since PHP 4");
        if (E_STRICT) $this->code[E_STRICT]=new phperror_code_class('E_STRICT',"Enable to have PHP suggest changes to your code which will ensure the best interoperability and forward compatibility of your code.  Since PHP 5 but not included in E_ALL until PHP 5.4.0");
        if (E_RECOVERABLE_ERROR) $this->code[E_RECOVERABLE_ERROR]=new phperror_code_class('E_RECOVERABLE_ERROR',"Catchable fatal error. It indicates that a probably dangerous error occured, but did not leave the Engine in an unstable state. If the error is not caught by a user defined handle (see also set_error_handler()), the application aborts as it was an E_ERROR.  Since PHP 5.2.0");
        if (E_DEPRECATED) $this->code[E_DEPRECATED]=new phperror_code_class('E_DEPRECATED',"Run-time notices. Enable this to receive warnings about code that will not work in future versions.  Since PHP 5.3.0");
        if (E_USER_DEPRECATED) $this->code[E_USER_DEPRECATED]=new phperror_code_class('E_USER_DEPRECATED',"User-generated warning message. This is like an E_DEPRECATED, except it is generated in PHP code by using the PHP function trigger_error().  Since PHP 5.3.0");
        if (E_ALL) $this->code[E_ALL]=new phperror_code_class('E_ALL',"All errors and warnings, as supported, except of level E_STRICT.  32767 in PHP 5.4.x, 30719 in PHP 5.3.x, 6143 in PHP 5.2.x, 2047 previously");
        if (!$decode) {
        	$this->error_decode=$this->error_reporting;
		  } else {
        	$this->error_decode=$decode;
		}
        foreach ($this->code as $key => $data) {
            if ( ($this->error_decode & $key) == $key) $this->decode[$key]=$data->name;
        }
	}
}
class phperror_code_class {
    var $name;
    var $description;
    function __construct($name,$description) {
        $this->name=$name;
        $this->description=$description;
    }
}
?>